name: Update Major Tag

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-tag:
    name: Update Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
          with:
            fetch-tags: true
        - id: extract
          run: echo "major=$(echo "$TAG" | cut -d. -f1)" >> $GITHUB_OUTPUT
          env:
            TAG: ${{ github.event.release.tag_name }}
        - run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -f $MAJOR
            git push origin $MAJOR --force
          env:
            MAJOR: ${{ steps.extract.outputs.major }}
