name: Update Major Tag

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  update-tag:
    name: Update Tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
        - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
          with:
            fetch-tags: true
        - id: extract
          run: echo "major=$(echo "$TAG" | cut -d. -f1)" >> $GITHUB_OUTPUT
          env:
            TAG: ${{ github.event.release.tag_name }}
        - run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git tag -f $MAJOR
            git push origin $MAJOR --force
          env:
            MAJOR: ${{ steps.extract.outputs.major }}
